repository: ekrishnas/ekrishnas.github.io
favicon: images/favicon.ico

version: 2

name: E Sai Krishna
title: Senior Software Engineer
email: krishnas1433@gmail.com
phone: +91-9908866642

darkmode: true

github_username: ekrishnas
stackoverflow_username: "5826312"
instagram_username: krishna_422
linkedin_username: krishna1433

about_title: Introduction
about_profile_image: images/profile.jpg
about_content: |
  I'm currently working as a senior software engineer at ValueMomentum. Experienced in web applications, backend services, building user interface and APIs, integration with external services, payment gateway integration and etc,. I'm current preparing for AWS Cloud Practitioner Certification. I'm most skilled in: <mark>.NET</mark> and <mark>AWS</mark>.

content:
  - title: Full Time Work Experience
    layout: list
    content:
      - layout: top-middle
        title: ValueMomentum
        link: https://valuemomentum.com/
        link_text: ValueMomentum Software Services
        sub_title: Senior Software Engineer
        caption: October 2022 - Present
        quote: >
          Scaling the initial product built to cater increasing business demand.
        description: | 
            - Setting up CI/CD using AWS SDK and GitHub Actions.
            - Converting existing monolithic architecture to microservices architecture.
            - Using pub-sub based communication to loosely couple services.
            - Maintain asynchronous communication where ever possible using messaging systems.
            - Building accelerators and write scripts to convert business specifications into system understandable files.
            - Talk to client, service team through daily meetings to better understand their problems and providing solutions along with implementation.
            - Refine backlogs, providing estimates and not only align team but to work with team to achieve target timelines.
            - Documenting architecture and solution to confluence for future reference.
            - Implementation of different cron jobs.

      - layout: top-middle
        title: ValueMomentum
        link: https://valuemomentum.com/
        link_text: ValueMomentum Software Services
        sub_title: Software Engineer
        caption: September 2019 - October 2022
        quote: >
          Development of an insurance-based product using APIs and plugins.
        description: |
            - Using APIs to communicate with [Socotra Policy Administration System](https://www.socotra.com/) for insurance policy issuance and policy servicing.
            - Working on generating invoices based on installments.
            - Converting business requirements into technical specifications and solutioning them.
            - Using JavaScript to write logic to configure a Price Quote (CPQ) Software, underwriting plugins.
            - Document generation using liquid templates and C# SDKs.
            - Third party integrations using GraphQL and HTTP requests.
            - [Stripe Payment Gateway setup](https://stripe.com/), integration and designing post payment processing workflows.
            - Generate documents and request for electronic signatures using third parties for compliance.
            - Using database to store relevant information related to quote and policy processing.
            - Writing stored procedures for database communication.
            - Building a mapping layer between two complicated systems for seamless integration between front end and backend.
            - Leading a team of seven to accomplish the business requirements.

      - layout: top-middle
        title: HashtagHyderabad
        sub_title: Director of Event Management
        caption: October 2017 - July 2019
        quote: >
          An event management company that worked on organizing events.
        description: | 
            - Meet with potential clients and converting the leads into business value.
            - Organize corporate, traditional, weddings, birthdays, business openings and media events.
            - Handle vendors from different backgrounds and bridge them together to conduct a pleasant experience.
      
      - layout: top-middle
        title: HCLTech
        link: https://www.hcltech.com/
        link_text: HCLTech
        sub_title: Product Support Engineer
        caption: April 2017 - August 2017
        quote: >
          Troubleshooting for Google's DoubleClick for Publisher clients like Microsoft, Motorola, Samsung, Apple etc.
        description: | 
            - Document software defects using a bug tracking system (JIRA) and report defects to software developers after initial analysis.
            - Gather information from user inquiries, read technical manuals, confer with users, conduct diagnostics to investigate and resolve problems by providing technical assistance.

      - layout: top-middle
        title: Tata Consultancy Services
        link: https://www.tcs.com/
        link_text: Tata Consultancy Services
        sub_title: Contract Assignee - Quality Assurance Engineer
        caption: January 2016 - October 2016
        quote: >
          Manual testing on Telecom Domain
        description: | 
            - Manual Testing of CRM tools like Salesforce, Oracle Communications Order and Service Management, Billing & Revenue Management (BRM) for a Philippines and a Canadian client.

  - title: Awards and Recognition
    layout: list
    content:
      - layout: left
        title: You Have Made a Difference
        sub_title: Issued by ValueMomentum
        caption: October 2022
        quote: >
          This award and recognition is awarded to an associate if they have made a significant change in a positive way to the company.
        description: |
          [Click me for certificate!](/images/VM_You have made a difference.png)

      - layout: left
        title: Highflier of the Quarter - Innovation
        sub_title: Issued by ValueMomentum
        caption: August 2021
        quote: >
          A Highflier award in Innovation category is awarded to an employee whose contribution has been innovative to the company and has made a difference to the company.
        description: |
          [Click me for certificate!](/images/VM_Highflier Innovation.png)

  - title: Prominent Skills
    layout: text
    content: |
      Following are the languages/tool that I have acquired a significant experience apart from my major skill set which were very useful during my work.
       - Python, JavaScript
       - HTML, CSS, jQuery, Markdown
       - YAML, JSON
       - Git, Git Workflows
       - Docker, CI/CD, GitHub & GitHub Actions
       - PDF/HTML Document Generation
       - Slack Apps, Webhooks and Integrations
       - Stripe Payment Gateway
       - Feature Management
       - Atlassian products like Jira and Confluence
       - Node.js, GraphQL, AWS Cloud Development Kit, AWS Amplify, AWS Secret Manager, AWS DynamoDB, AWS CloudWatch, AWS IAM, AWS Lambda, AWS SNS, AWS SQS.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Bachelor of Technology
        caption: 2011 - 2015
        sub_title: Keshav Memorial Institute of Technology
        quote: >
          Obtained bachelors degree with 67% in Electronics and Communications Engineering in Hyderabad from Jawaharlal Nehru Technological University.

      - layout: left
        title: Intermediate Education
        caption: 2009 - 2011
        sub_title: Sri Chaitanya College
        quote: >
          Completed intermediate education with 74% in Hyderabad by obtaining certification from State Board of Intermediate Education.
      
      - layout: left
        title: Schooling
        caption: 1997 - 2009
        sub_title: Don Bosco High School
        quote: >
          Completed schooling with 85% Hyderabad, with certification from State Board of Secondary Education.

  # - title: Projects
  #   layout: list
  #   content:
  #     - layout: top-middle
  #       title: Authentication
  #       link: github.com/ekrishnas/
  #       link_text: Project Website
  #       additional_links:
  #         - title:  ekrishnas/authentication
  #           icon: fab fa-github
  #           url: github.com/ekrishnas/authentication
  #       quote: >
  #         This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
  #       description: |
  #         I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
