repository: ekrishnas/ekrishnas.github.io
favicon: images/favicon.ico
version: 2
name: E Sai Krishna
title: Senior Software Engineer
email: krishnas1433@gmail.com
phone: +91-9908866642
web: https://ekrishnas.github.io/
darkmode: true
github_username: ekrishnas
stackoverflow_username: '5826312'
linkedin_username: krishna1433
about_title: Introduction
about_profile_image: images/profile.jpg
about_content: |
  A senior software engineer with 7 years of experience in C#, AWS and excelling in web applications, integrations, backend services, and building APIs.
content:
  - title: Full Time Work Experience
    layout: list
    content:
      - layout: top-middle
        title: Senior Software Engineer
        link: https://www.epam.com/
        link_text: EPAM Systems
        sub_title: EPAM Systems
        caption: '2024 - Present'
        quote: |
          Understand business requirements to debug and provide operational support by fixing performance issues for complex and legacy .NET Application systems. Analyzing and migrating existing batching system to Hangfire background jobs.
        description: |
          - Design, develop and maintain software solutions using .NET core, .NET Framework, Angular and PostgreSQL.
          - Analyze code base and propose solutions to mitigate performance issues.
          - Analyze existing infrastructure to understand how the application is working and performing in AWS, to deliver solutions.
          - Collaborate with teams to ensure the proposed design following the architectural roadmap and adhere to established standards and policies.
          - Work in collaboration with the client, update the inputs regarding the mitigation plan, and ensure the client is informed and is in agreement about the proposed solution.
          - Creating a project and solution from scratch for migrating background batch jobs to Hangfire for more performant queueing system for background jobs.
          - Worked with Windows services and is able to integrate with Windows services using WCF.
          - Expereince in working with websocket for front end notifications that speard progress over multiple individual jobs.
          - Ability to leverage LLMs, Model Context Protocol  in building applications that require AI agents.
          - Use agents like GitHub copilot and Cline to cut down developement efforts by 80%.

      - layout: top-middle
        title: Senior Software Engineer
        link: https://valuemomentum.com/
        link_text: ValueMomentum
        sub_title: ValueMomentum Software Services
        caption: '2022 - 2024'
        quote: |
          Scaled the initial product to meet increasing business demand by guiding the team in client collaboration, ensuring comprehension of requirements, and proposing technical workflows.
        description: |
          - Validated specifications improved team delivery by 30% for a sprint by decreasing turnaround time.
          - Proposed infrastructure changes based on business requirements, resolving bulk quote conversion issues and increasing revenue by 60%.
          - Managed Jira administration, Git branching, and workflows, documenting architecture and solutions for future reference and team-wide understanding.
          - Pioneered CI/CD implementation using AWS SDK and GitHub Actions, achieving a 50% enhancement in continuous integration efficiency.
          - Orchestrated the transition to microservices architecture, reducing errors and improving performance by 6 seconds.
          - Migration of data from existing tables to updated tables after transition for seamless experience.
          - Implemented an event-driven architecture with pub-sub-based communication protocols, eliminating regression issues by 40%.
          - Developed accelerators and scripted processes, thereby expediting development workflows by at least 3 days.
          - Automated diverse batch jobs, enhancing system efficiency and saving the service team 2 days a week.
          - Setup and designed post-payment processing workflows for the [Stripe Payment Gateway](https://stripe.com/).

      - layout: top-middle
        title: Software Engineer
        link: https://valuemomentum.com/
        link_text: ValueMomentum
        sub_title: ValueMomentum Software Services
        caption: 2019 - 2022
        quote: |
          Development of an insurance-based product using APIs, plugins, incorporating third party APIs and invoicing collection.
        description: |
          - Designed and implemented APIs to communicate with the Socotra Policy Administration System for insurance policy issuance and servicing. Incorporated third-party integration using GraphQL and HTTP requests for quote generation.
          - Developed logic to price a quote and get automated underwriting approval in less than 5 seconds, plan invoices, and automating invoice collection thereby reducing service team dependency by one day.
          - Achieved PDF and HTML document generation using liquid templates, later transitioning to Razor templates with C# SDKs, reducing document generation time by at least 5 seconds.
          - Constructed a mapping layer and Authored stored procedures for streamlined database communication, facilitating integration and communication between front-end and back-end systems, resulting in reasonable response times by at least 3 seconds.

      - layout: top-middle
        title: Director
        sub_title: HashtagHyderabad
        caption: 2017 - 2019
        quote: |
          An event management company that designs and executes events for individuals and organizations.
        description: |
          - Conducted meetings with potential clients, converting leads into tangible business, orchestrated events like corporate & personal events by coordinating with vendors from diverse backgrounds to create a cohesive and pleasant event experience.

      - layout: top-middle
        title: Product Support Engineer
        link: https://www.hcltech.com/
        link_text: HCLTech
        sub_title: HCLTech
        caption: 2017 - 2017
        quote: |
          Diagnosed for Google's DoubleClick for Publisher clients like Microsoft, Motorola, Samsung, Apple.
        description: | 
         - Documented software defects in JIRA, reported to developers after initial analysis, and provided technical assistance by investigating and resolving problems based on user inquiries and diagnostics.

      - layout: top-middle
        title: Quality Assurance Engineer
        link: https://www.tcs.com/
        link_text: Tata Consultancy Services
        sub_title: Tata Consultancy Services
        caption: 2016 - 2016
        quote: |
          Manual testing on Telecom Domain
        description: |
          - Executed manual testing of CRM tools, encompassing Salesforce and Oracle Communications with products like Order & Service Management, Billing & Revenue Management (BRM), for clients in both the Philippines and Canada.

  - title: Certifications
    layout: text
    content: |
          - [Google Cloud: Generative AI Leader (June 2025)](https://www.credly.com/badges/2290cd1e-91ab-412e-a693-14ed54a8c6c4/public_url)
          - [AWS Partner: Technical Accredited (August 2024)](https://www.credly.com/badges/f5b353ba-f4c3-4ca5-bbcb-7b9a9488b394/public_url)
          - [More..](https://www.linkedin.com/in/ekrishnas/details/certifications/)
          
  - title: Awards and Recognition
    layout: text
    content: |
          - EPAM Systems - 
          - ValueMomentum - Highflier of the Quarter - Innovation (2021)
          - ValueMomentum - Made a Difference - Annual award (2022)

  - title: Prominent Skills
    layout: text
    content: |
      Languages/tools with significant experience, beyond the main skill set, were valuable during work.
       - C#, .NET Web Apps, HTML, CSS, jQuery, Markdown, Python, JavaScript
       - Git, Git Workflows, Docker, CI/CD, GitHub & GitHub Actions, Feature Management, Jira and Confluence
       - Slack Apps, Webhooks, Stripe, OneInc Payment Gateway
       - Node.js, GraphQL, AWS CDK, AWS Amplify, AWS Secret Manager, AWS DynamoDB, AWS CloudWatch, AWS IAM, AWS Lambda, AWS SNS, AWS SQS.
       - Azure Function Apps, Azure DevOps

  - title: Education
    layout: list
    content:
      - layout: top-middle
        title: Bachelor of Technology
        caption: '2015'
        sub_title: Keshav Memorial Institute of Technology
        quote: |
          Obtained bachelors degree with 67% in Electronics and Communications from Jawaharlal Nehru Technological University.

footer_show_references: false
remote_theme: sproogen/resume-theme
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-seo-tag
Transform: AWS::Serverless-2016-10-31