repository: ekrishnas/ekrishnas.github.io
favicon: images/favicon.ico

version: 2

name: E Sai Krishna
title: Senior Software Engineer
email: krishnas1433@gmail.com
phone: +91-9908866642

darkmode: true

github_username: ekrishnas
stackoverflow_username: "5826312"
instagram_username: krishna_422
linkedin_username: krishna1433

about_title: Introduction
about_profile_image: images/profile.jpg
about_content: |
  I'm a senior software engineer. I have experience making software and web apps. 
  I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>.NET</mark>, <mark>DevOps</mark>, <mark>AWS</mark>.

content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: Authentication
        link: github.com/ekrishnas/
        link_text: Project Website
        additional_links:
          - title:  ekrishnas/authentication
            icon: fab fa-github
            url: github.com/ekrishnas/authentication
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: |
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience
    layout: list
    content:
      - layout: left
        title: ValueMomentum
        link: https://valuemomentum.com/
        link_text: ValueMomentum
        sub_title: Senior Software Engineer
        caption: October 2022 - Present
        quote: >
          Solving 21st century problems by  and making game changing products like the *not a flamethrower*
        description: | 
            Every company needs its networks properly administered and The Boring is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
     
      - layout: left
        title: ValueMomentum
        link: https://valuemomentum.com/
        link_text: ValueMomentum
        sub_title: Software Engineer
        caption: September 2019 - October 2022
        quote: >
          Solving 21st century problems by  and making game changing products like the *not a flamethrower*
        description: |
            Every company needs its networks properly administered and The Boring is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

      - layout: left
        title: HashtagHyderabad
        sub_title: Director of Event Management
        caption: October 2017 - July 2019
        quote: >
          Solving 21st century problems by  and making game changing products like the *not a flamethrower*
        description: | 
            Every company needs its networks properly administered and The Boring is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.
      
      - layout: left
        title: HCLTech
        link: https://www.hcltech.com/
        link_text: HCLTech
        sub_title: Product Support Engineer
        caption: April 2017 - August 2017
        quote: >
          Solving 21st century problems by  and making game changing products like the *not a flamethrower*
        description: | 
            Every company needs its networks properly administered and The Boring is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

      - layout: left
        title: Tata Consultancy Services
        link: https://www.tcs.com/
        link_text: Tata Consultancy Services
        sub_title: Contract Assignee
        caption: January 2016 - October 2016
        quote: >
          Solving 21st century problems by  and making game changing products like the *not a flamethrower*
        description: | 
            Every company needs its networks properly administered and The Boring is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Bachelor of Technology
        caption: 2011 - 2015
        sub_title: Keshav Memorial Institute of Technology
        quote: >
          Obtained bachelors degree with 67% in Electronics and Communications Engineering in Hyderabad from Jawaharlal Nehru Technological University.

      - layout: left
        title: Intermediate Education
        caption: 2009 - 2011
        sub_title: Sri Chaitanya College
        quote: >
          Completed intermediate education with 74% in Hyderabad by obtaining certification from State Board of Intermediate Education.
      
      - layout: left
        title: Schooling
        caption: 1997 - 2009
        sub_title: Don Bosco High School
        quote: >
          Completed schooling with 85% Hyderabad, with certification from State Board of Secondary Education.



  - title: Skills of mine that can be useful
    layout: text
    content: |
      Following are the languages/tool that I have an experience in apart from my major skills which can be useful
       - Python, JavaScript
       - HTML, CSS, jQuery
       - Git, Git Workflows
       - CI/CD, GitHub & GitHub Actions
       - PDF/HTML Document Generation
       - Slack Apps, Webhooks and Integrations
       - Stripe Payment Gateway
       - Feature Management
       - AWS serverless architecture
       - AWS SNS and SQS


# Footer
footer_show_references: false
# references_title: References on request (Override references text)

remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
