# Site
repository: ekrishnas/ekrishnas.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: E Sai Krishna
title: Senior Software Engineer
email: krishnas1433@gmail.com
phone: +919908866642
# website: https://www.linkedin.com/in/krishna1433/

# Dark Mode (true/false/never)
darkmode: true

# Social links
github_username: ekrishnas
stackoverflow_username: "5826312"
instagram_username: krishna_422
linkedin_username: krishna1433

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Sai Krishna and I'm a senior software engineer. I have experience making software and web apps. 
  I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>.NET</mark>, <mark>DevOps</mark>, <mark>AWS</mark>.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: B.Tech
        caption: 2011 - 2015
        sub_title: Keshav Memorial Institute of Technology
        quote: >
          Obtained bachelors degree in Electronics and Communications Engineering in Hyderabad from Jawaharlal Nehru Technological University.

      - layout: left
        title: Intermediate Education
        caption: 2009 - 2011
        sub_title: Sri Chaitanya College
        quote: >
          Completed intermediate education in Hyderabad by obtaining certification from State Board of Intermediate Education.
      
      - layout: left
        title: SSC
        caption: 1997 - 2009
        sub_title: Don Bosco High School
        quote: >
          Completed schooling in Hyderabad, with certification from State Board of Secondary Education.



  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
