repository: ekrishnas/ekrishnas.github.io
favicon: images/favicon.ico
version: 2
name: E Sai Krishna
title: Senior Software Engineer
email: krishnas1433@gmail.com
phone: +91-9908866642
darkmode: true
github_username: ekrishnas
stackoverflow_username: '5826312'
linkedin_username: krishna1433
about_title: Introduction
about_profile_image: images/profile.jpg
about_content: |
  A senior software engineer with five years of experience in .NET and AWS working at ValueMomentum, excelling in web applications, backend services, UI/UX development, and building API that serves at least 10,000 requests per day. Currently pursuing AWS Cloud Practitioner Certification.
content:
  - title: Full Time Work Experience
    layout: list
    content:
      - layout: top-middle
        title: Senior Software Engineer
        link: https://valuemomentum.com/
        link_text: ValueMomentum
        sub_title: ValueMomentum Software Services
        caption: '2022'
        quote: |
          Scaled the initial product to meet increasing business demand by guiding the team in client collaboration, ensuring comprehension of requirements, and proposing technical workflows.
        description: |
          - Validated specifications improved team delivery by 30% for a sprint by decreasing turnaround time.
          - Proposed infrastructure changes based on business requirements, resolving bulk quote conversion issues and increasing revenue by 60%.
          - Managed Jira administration, Git branching, and workflows, documenting architecture and solutions for future reference and team-wide understanding.
          - Pioneered CI/CD implementation using AWS SDK and GitHub Actions, achieving a 50% enhancement in continuous integration efficiency.
          - Orchestrated the transition to microservices architecture, reducing errors and improving performance by 6 seconds.
          - Implemented an event-driven architecture with pub-sub-based communication protocols, eliminating regression issues by 40%.
          - Developed accelerators and scripted processes, thereby expediting development workflows by at least 3 days.
          - Automated diverse batch jobs, enhancing system efficiency and saving the service team 2 days a week.
          - Setup and designed post-payment processing workflows for the [Stripe Payment Gateway](https://stripe.com/).

      - layout: top-middle
        title: Software Engineer
        link: https://valuemomentum.com/
        link_text: ValueMomentum
        sub_title: ValueMomentum Software Services
        caption: 2019 - 2022
        quote: |
          Development of an insurance-based product using APIs, plugins, incorporating third party APIs and invoicing collection.
        description: |
          - Designed and implemented APIs to communicate with the [Socotra Policy Administration System](https://www.socotra.com/) for insurance policy issuance and servicing by incorporating third-party integrations using GraphQL and HTTP requests for quote generation.
          - Developed installment plan invoices and automated workflows, reducing service team dependency by one day.
          - Applied JavaScript logic to configure a Price Quote (CPQ) Software, resulting in quotes and approval in less than 3 seconds.
          - Achieved PDF and HTML document generation using liquid templates, later transitioning to Razor templates with C# SDKs, reducing document generation time by at least 5 seconds and electronic signatures through third-party tools to ensure compliance.
          - Authored stored procedures for streamlined database communication, maintaining uniformity across code.
          - Constructed a mapping layer, facilitating integration and communication between front-end and back-end systems, resulting in reasonable response times by at least 3 seconds.

      - layout: top-middle
        title: Director
        sub_title: HashtagHyderabad
        caption: 2017 - 2019
        quote: |
          An event management company that designs and executes events for individuals and organizations.
        description: |
          - Conducted meetings with potential clients, converting leads into tangible business value, orchestrated events, including corporate gatherings, weddings, birthdays, business openings by coordinating with vendors from diverse backgrounds to create a cohesive and pleasant event experience.

      - layout: top-middle
        title: Product Support Engineer
        link: https://www.hcltech.com/
        link_text: HCLTech
        sub_title: HCLTech
        caption: 2017 - 2017
        quote: |
          Diagnosed for Google's DoubleClick for Publisher clients like Microsoft, Motorola, Samsung, Apple.
        description: | 
         - Documented software defects in JIRA, reported to developers after initial analysis, and provided technical assistance by investigating and resolving problems based on user inquiries and diagnostics.

      - layout: top-middle
        title: Quality Assurance Engineer
        link: https://www.tcs.com/
        link_text: Tata Consultancy Services
        sub_title: Tata Consultancy Services
        caption: 2016 - 2016
        quote: |
          Manual testing on Telecom Domain
        description: |
          - Executed manual testing of CRM tools, encompassing Salesforce and Oracle Communications with products like Order & Service Management, Billing & Revenue Management (BRM), for clients in both the Philippines and Canada.

  - title: Awards and Recognition
    layout: list
    content:
      - layout: top-middle
        title: Made a Difference - Annual award.
        sub_title: ValueMomentum
        caption: '2022'
        quote: |
          The company awards associates who make a significant positive difference.
      - layout: top-middle
        title: Highflier of the Quarter - Innovation.
        sub_title: ValueMomentum
        caption: '2021'
        quote: |
          An employee, whose innovative contribution has made a significant difference.

  - title: Prominent Skills
    layout: text
    content: |
      Languages/tools with significant experience, beyond the main skill set, were valuable during work.
       - Python, JavaScript
       - HTML, CSS, jQuery, Markdown
       - YAML, JSON
       - Git, Git Workflows
       - Docker, CI/CD, GitHub & GitHub Actions
       - PDF/HTML Document Generation
       - Slack Apps, Webhooks & Integrations
       - Stripe Payment Gateway
       - Feature Management
       - Jira and Confluence
       - Node.js, GraphQL, AWS Cloud Development Kit, AWS Amplify, AWS Secret Manager, AWS DynamoDB, AWS CloudWatch, AWS IAM, AWS Lambda, AWS SNS, AWS SQS.

  - title: Education
    layout: list
    content:
      - layout: left
        title: Bachelor of Technology
        caption: '2015'
        sub_title: Keshav Memorial Institute of Technology
        quote: |
          Obtained bachelors degree with 67% in Electronics and Communications from Jawaharlal Nehru Technological University.
footer_show_references: false
remote_theme: sproogen/resume-theme
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-seo-tag
Transform: AWS::Serverless-2016-10-31